export enum TransferStatus {
  TO_SERVE="TO_SERVE",
  SERVED="SERVED",
  CANCELED="CANCELED",
  RETURNED="RETURNED",
  BLOCKED="BLOCKED",
  UNBLOCKED="UNBLOCKED",
  EXPIRED="EXPIRED",
  WAITING="WAITING",
}
